% Machine Learning HW#3
% By: Seyed Mohammad Hossein Oloomi

function maze(action)
if nargin<1
    % set up a working figure window and store it in the userdata for
    % action 'setup' to use
    figure_h=figure;
    set(figure_h,'Units','points')
    %set(figure_h,'UserData',figure_h);
    action='initialize';
end

switch action
    case 'initialize';
        % StepReward WallReward HoleReward StartReward GoalReward
        data.rewards = [-1 -1 -10 -1 100];
        data.rownum = 5;
        data.colnum = 5;
        data.cellSize = 22;
        data.goalReward = 100;
        data.holeReward = -10;
        data.stepReward = -1;
        data.discountFactor = 0.6;
        data.sParameter = 0.02;
        data.episodLength = 50;
        data.white = [1 1 1];
        data.gray = [0.5 0.5 0.5];
        data.orange = [1 0.6 0.2];
        data.blue = [0 0 1];
        data.green = [0 1 0];
        data.startRow = -1;
        data.startCol = -1;
        data.goalRow = -1;
        data.goalCol = -1;

        % Thanks to Hesam Alizadeh for helping me in GUI
        set(figure_h,...
            'Color',[0.4 0.4 0.4],...
            'Menubar','none',...
            'Name','Maze',...
            'NumberTitle','off',...
            'Position',[50 50 600 500]);
        axis('off')
        
        % Number of Rows Input
        % label
        uicontrol(figure_h,...
            'FontSize',10, ...
            'Units','points',...
            'Position',[10 475 75 15],...
            'ForegroundColor',[1 1 1], ...
            'BackgroundColor',[0.4 0.4 0.4],...
            'String','Rows',...
            'Style','text');
        % textbox
        uicontrol(figure_h,...
            'Callback','maze rownum',...
            'FontSize',10, ...
            'Units','points',...
            'Position',[10 460 75 15],...
            'String','5',...
            'Style','edit');

        % Number of Columns Input
        % label
        uicontrol(figure_h,...
            'FontSize',10, ...
            'Units','points',...
            'Position',[10 435 70 15],...
            'ForegroundColor',[1 1 1], ...
            'BackgroundColor',[0.4 0.4 0.4],...
            'String','Columns',...
            'Style','text');
        % textbox
        uicontrol(figure_h,...
            'Callback','maze colnum',...
            'FontSize',10, ...
            'Units','points',...
            'Position',[10 420 75 15],...
            'String','5',...
            'Style','edit');

        % Goal Reward Input
        % label
        uicontrol(figure_h,...
            'FontSize',10, ...
            'Units','points',...
            'Position',[10 395 75 15],...
            'ForegroundColor',[0 1 0], ...
            'BackgroundColor',[0.4 0.4 0.4],...
            'String','Goal Reward',...
            'Style','text');
        % textbox
        uicontrol(figure_h,...
            'Callback','maze goalReward',...
            'FontSize',10, ...
            'Units','points',...
            'Position',[10 380 75 15],...
            'String','100',...
            'Style','edit');

        % Hole Reward Input
        % label
        uicontrol(figure_h,...
            'FontSize',10, ...
            'Units','points',...
            'Position',[10 355 75 15],...
            'ForegroundColor',[1 0.6 0.2], ...
            'BackgroundColor',[0.4 0.4 0.4],...
            'String','Hole Reward',...
            'Style','text');
        % textbox
        uicontrol(figure_h,...
            'Callback','maze holeReward',...
            'FontSize',10, ...
            'Units','points',...
            'Position',[10 340 75 15],...
            'String','-10',...
            'Style','edit');

        % Step Reward Input
        % label
        uicontrol(figure_h,...
            'FontSize',10, ...
            'Units','points',...
            'Position',[10 315 75 15],...
            'ForegroundColor',[1 1 1], ...
            'BackgroundColor',[0.4 0.4 0.4],...
            'String','Step Reward',...
            'Style','text');
        % textbox
        uicontrol(figure_h,...
            'Callback','maze stepReward',...
            'FontSize',10, ...
            'Units','points',...
            'Position',[10 300 75 15],...
            'String','-1',...
            'Style','edit');

        % Discount Factor Input
        % label
        uicontrol(figure_h,...
            'FontSize',10, ...
            'Units','points',...
            'Position',[10 275 75 15],...
            'ForegroundColor',[1 1 1], ...
            'BackgroundColor',[0.4 0.4 0.4],...
            'String','Discount Factor',...
            'Style','text');
        % textbox
        uicontrol(figure_h,...
            'Callback','maze discountFactor',...
            'FontSize',10, ...
            'Units','points',...
            'Position',[10 260 75 15],...
            'String','0.6',...
            'Style','edit');

        % S Parameter Input
        % label
        uicontrol(figure_h,...
            'FontSize',10, ...
            'Units','points',...
            'Position',[10 235 75 15],...
            'ForegroundColor',[1 1 1], ...
            'BackgroundColor',[0.4 0.4 0.4],...
            'String','S Parameter',...
            'Style','text');
        % textbox
        uicontrol(figure_h,...
            'Callback','maze sParameter',...
            'FontSize',10, ...
            'Units','points',...
            'Position',[10 220 75 15],...
            'String','0.02',...
            'Style','edit');

        % Episod Length Input
        % label
        uicontrol(figure_h,...
            'FontSize',10, ...
            'Units','points',...
            'Position',[10 195 75 15],...
            'ForegroundColor',[1 1 1], ...
            'BackgroundColor',[0.4 0.4 0.4],...
            'String','Episod Length',...
            'Style','text');
        % textbox
        uicontrol(figure_h,...
            'Callback','maze episodLength',...
            'FontSize',10, ...
            'Units','points',...
            'Position',[10 180 75 15],...
            'String','50',...
            'Style','edit');

        % Submit
        uicontrol(figure_h,...
            'Callback','maze submit',...
            'Fontsize',10, ...
            'Units','points',...
            'Position',[10 15 80 20],...
            'String','Create Maze',...
            'Style','pushbutton');

        % Policy Iteration
        uicontrol(figure_h,...
            'Callback','policy_iteration',...
            'Fontsize',10, ...
            'Units','points',...
            'Position',[200 15 80 20],...
            'String','Policy Iteration',...
            'Style','pushbutton');

        % Value Iteration
        uicontrol(figure_h,...
            'Callback','value_iteration',...
            'Fontsize',10, ...
            'Units','points',...
            'Position',[290 15 80 20],...
            'String','Value Iteration',...
            'Style','pushbutton');

        % On policy Monte Carlo
        uicontrol(figure_h,...
            'Callback','monte_carlo',...
            'Fontsize',10, ...
            'Units','points',...
            'Position',[380 15 80 20],...
            'String','Monte Carlo',...
            'Style','pushbutton');

        set(figure_h,'UserData',data);

    case 'rownum'
        data = get(gcf,'UserData');
        data.rownum = str2num(get (gcbo, 'String') );
        set (gcf, 'UserData', data);
    case 'colnum'
        data = get(gcf,'UserData');
        data.colnum = str2num(get (gcbo, 'String') );
        set (gcf, 'UserData', data);
    
        % StepReward WallReward HoleReward StartReward GoalReward
    case  'stepReward'
        data = get(gcf,'UserData');
        data.stepReward = str2num(get (gcbo, 'String') );
        data.rewards(1)= data.stepReward;
        set (gcf, 'UserData', data);
    case  'holeReward'
        data = get(gcf,'UserData');
        data.holeReward = str2num(get (gcbo, 'String') );
        data.rewards(3)= data.holeReward;
        set (gcf, 'UserData', data);
    case  'goalReward'
        data = get(gcf,'UserData');
        data.goalReward = str2num(get (gcbo, 'String') );
        data.rewards(5)= data.goalReward;
        set (gcf, 'UserData', data);
  
    case  'discountFactor'
        data = get(gcf,'UserData');
        data.discountFactor = str2num(get (gcbo, 'String') );
        set (gcf, 'UserData', data);
    case  'sParameter'
        data = get(gcf,'UserData');
        data.sParameter= str2num(get (gcbo, 'String') );
        set (gcf, 'UserData', data);
    case  'episodLength'
        data = get(gcf,'UserData');
        data.episodLength = str2num(get (gcbo, 'String') );
        set (gcf, 'UserData', data);

    case 'submit'
        data = get(gcf,'UserData');
        RN = data.rownum;
        CN = data.colnum;
        data.cell_handle = zeros(RN,CN);
        data.cell_type = ones(RN,CN);        
        data.agentRow = -1;
        data.agentCol = -1;

        squareSize = data.cellSize;
        for i=1:RN
            for j=1:CN
                position=[90+(squareSize*j) 40+(squareSize*i) squareSize squareSize];
                data.cell_handle(i, j)=uicontrol(gcf,...
                    'Callback','maze change_cell',...
                    'FontSize',10,...                    
                    'Units','points',...                    
                    'BackgroundColor', [1 1 1],...
                    'ForegroundColor', [0 0 0],...
                    'Position',position,...
                    'String','',...
                    'Style','pushbutton');
            end
        end
        set (gcf, 'UserData', data);

    case 'change_cell'
        data = get(gcf,'UserData');
        cellPosition = get(gcbo, 'Position');
        squareSize = data.cellSize;
        colIndex = (cellPosition(1) - 90) / squareSize;
        rowIndex = (cellPosition(2) - 40) / squareSize;
        if (data.cell_type(rowIndex, colIndex) == 5)
            data.cell_type(rowIndex, colIndex) = 1;
            set(data.cell_handle(rowIndex, colIndex), 'BackgroundColor' , data.white);
            data.goalRow = -1;
            data.goalCol = -1;
        else
            data.cell_type(rowIndex, colIndex) = data.cell_type(rowIndex, colIndex) + 1;
            if (data.cell_type(rowIndex, colIndex) == 2)        % Wall
                set(data.cell_handle(rowIndex, colIndex), 'BackgroundColor' , data.gray);

            elseif (data.cell_type(rowIndex, colIndex) == 3)    % Hole
                set(data.cell_handle(rowIndex, colIndex), 'BackgroundColor' , data.orange);

            elseif (data.cell_type(rowIndex, colIndex) == 4)    % Start state
                set(data.cell_handle(rowIndex, colIndex), 'BackgroundColor' , data.blue);
                if (data.startRow == -1)
                    data.startRow = rowIndex;
                    data.startCol = colIndex;
                else
                    set(data.cell_handle(data.startRow, data.startCol), 'BackgroundColor' , data.white);
                    data.cell_type(data.startRow, data.startCol) = 1;
                    data.startRow = rowIndex;
                    data.startCol = colIndex;
                end

            elseif (data.cell_type(rowIndex, colIndex) == 5)    % Goal state
                set(data.cell_handle(rowIndex, colIndex), 'BackgroundColor' , data.green);
                data.startRow = -1;
                data.startCol = -1;
                if (data.goalRow == -1)
                    data.goalRow = rowIndex;
                    data.goalCol = colIndex;
                else
                    set(data.cell_handle(data.goalRow, data.goalCol), 'BackgroundColor' , data.white);
                    data.cell_type(data.goalRow, data.goalCol) = 1;
                    data.goalRow = rowIndex;
                    data.goalCol = colIndex;
                end
            end
        end
        set (gcf, 'UserData', data);   
    otherwise
        disp([mfilename ': unknown action ''' action ''''])
end
end